version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bankcards-db
    restart: always
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bankcards"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: bankcards-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankcards
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass
      JWT_SECRET: myamyamyamya123!@#supersecretkey2025
    ports:
      - "8080:8080"

volumes:
  pgdata:
